<header class="bg-background-secondary px-20 py-5 flex justify-end  w-full">
    <button
        class="bg-primary font-inter text-4xl font-extrabold min-w-20 min-h-20 w-20 h-20 rounded-xl border-black border-2 cursor-pointer transition-transform duration-300 hover:rotate-12">
        L
    </button>
</header>
<main class="bg-background-secondary mt-6 px-12 flex-1 flex items-center justify-center">
    <div class="mx-auto w-1/2 min-w-[36rem] px-6 rounded-lg border-2 border-black bg-background">
        <div class="flex justify-end">
            <a href="/" class="group bg-white font-inter text-lg font-extrabold px-4 py-1 mt-4 rounded-full border-black border-2 inline-flex items-center gap-1 cursor-pointer">
                <svg class="w-4 h-4 inline-block transition-transform duration-200 rotate-45 group-hover:rotate-[135deg]"
                    viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path d="M10 1H6V6L1 6V10H6V15H10V10H15V6L10 6V1Z" />
                </svg>
                CLOSE
            </a>
        </div>
        <h1 class="font-inter font-extrabold text-2xl px-8 pt-6 pb-2">TITLE</h1>
        <input placeholder="This task needs a title..." class="rounded-lg border-black border-2 h-10 px-4 w-full cursor-text"></input>

        <h1 class="font-inter font-extrabold text-2xl px-8 pt-6 pb-2">DESCRIPTION</h1>
        <textarea placeholder="This task needs a description..." class="rounded-lg border-black border-2 h-10 px-4 py-2 mb-4 w-full h-32 cursor-text"></textarea>
        <div class="flex-1 flex justify-center mb-6">
            <button
                class="group bg-primary font-inter text-4xl font-extrabold py-4 px-6 rounded-full border-black border-2 cursor-pointer flex items-center justify-center gap-3">
                <svg class="w-6 h-6 inline-block transition-transform duration-300 group-hover:rotate-90"
                    viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path d="M10 1H6V6L1 6V10H6V15H10V10H15V6L10 6V1Z" />
                </svg>
                ADD
            </button>
        </div>
    </div>
    </div>
</main>