<header class="py-16 bg-background-secondary"></header>

<main class="flex items-center justify-center flex-1 px-12 bg-background-secondary">
    <div class="w-1/2 min-w-[24rem] md:min-w-[36rem] mx-auto px-6 bg-background border-2 border-black rounded-lg">
        <div class="flex justify-end">
            <a href="/" class="inline-flex items-center gap-1 px-4 py-1 mt-4 bg-white border-2 border-black rounded-full cursor-pointer font-inter text-lg font-extrabold group">
                <svg class="w-4 h-4 rotate-45 transition-transform duration-200 group-hover:rotate-[135deg]" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path d="M10 1H6V6L1 6V10H6V15H10V10H15V6L10 6V1Z" />
                </svg>
                CLOSE
            </a>
        </div>

        <form action="/task/store" method="POST">
            <h1 class="px-8 pt-6 pb-2 font-inter text-2xl font-extrabold">TITLE</h1>

            <input type="text" name="title" value="<?= @$_POST['title'] ?>" required placeholder="This task needs a title..." class="w-full h-10 px-4 border-2 border-black rounded-lg cursor-text">
            
            <h1 class="px-8 pt-6 pb-2 font-inter text-2xl font-extrabold">DESCRIPTION</h1>
            
            <textarea name="description" required placeholder="Also a description!" class="w-full h-32 px-4 py-2 border-2 border-black rounded-lg cursor-text"><?= @$_POST['description'] ?></textarea>
            
            <h1 class="px-8 pt-4 pb-2 font-inter text-2xl font-extrabold">CREATED BY</h1>
            
            <input type="text" name="user" value="<?= @$_POST['user'] ?>" required placeholder="Who is adding this?" class="w-full h-10 px-4 mb-6 border-2 border-black rounded-lg cursor-text">
            
            <div class="flex justify-center flex-1 mb-6">
                <button type="submit" class="flex items-center justify-center gap-3 px-4 py-2 md:px-6 md:py-4 bg-primary border-2 border-black rounded-full cursor-pointer font-inter xl:text-4xl text-2xl font-extrabold group">
                    <svg class="inline-block xl:w-6 xl:h-6 md:w-5 md:h-5 w-4 h-4 transition-transform duration-300 group-hover:rotate-90" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path d="M10 1H6V6L1 6V10H6V15H10V10H15V6L10 6V1Z" />
                    </svg>
                    ADD
                </button>
            </div>
        </form>
    </div>
</main>