 <header class="bg-background-secondary px-20 py-5">
     <div class="flex-1 flex justify-end">
         <button class="bg-primary font-inter text-4xl font-extrabold min-w-20 min-h-20 w-20 h-20 rounded-xl border-black border-2 cursor-pointer transition-transform duration-300 hover:rotate-12">
             L
         </button>
     </div>
 </header>

 <main class="bg-background-secondary px-12">
     <div class="mx-auto w-1/2 min-w-[36rem] px-6 rounded-lg border-2 border-black bg-background flex flex-col">
         <a
             href="/task/<?= $this->task['id'] ?>"
             class="self-end inline-flex items-center gap-1 mt-4 px-3 py-1 rounded-full border-2 border-black bg-white font-inter text-lg font-extrabold group cursor-pointer">
             <svg
                 class="w-4 h-4 transition-transform duration-200 rotate-45 group-hover:rotate-[135deg]"
                 viewBox="0 0 16 16"
                 fill="currentColor"
                 xmlns="http://www.w3.org/2000/svg">
                 <path d="M10 1H6V6L1 6V10H6V15H10V10H15V6L10 6V1Z" />
             </svg>
             CLOSE
         </a>

         <form action="/task/update" method="POST">

             <input type="hidden" name="id" value="<?= $this->task['id'] ?>">

             <h1 class="font-inter font-extrabold text-2xl px-12 pt-6 pb-2">TITLE</h1>
             <input
                 type="text"
                 name="title"
                 value="<?= htmlspecialchars($this->task['title']) ?>"
                 class="rounded-lg border-black border-2 h-10 px-4 w-full cursor-text">

             <h1 class="font-inter font-extrabold text-2xl px-12 pt-6 pb-2">DESCRIPTION</h1>
             <textarea
                 name="description"
                 class="rounded-lg border-black border-2 px-4 py-2 mb-4 w-full h-32 cursor-text"><?= htmlspecialchars($this->task['description']) ?></textarea>

             <div class="flex-1 flex justify-center mb-6">
                 <button
                     type="submit"
                     class="bg-white font-inter text-4xl font-extrabold py-4 px-6 rounded-full border-black border-2 hover:bg-primary cursor-pointer">
                     EDIT
                 </button>
             </div>

         </form>
     </div>
 </main>