 <header class="px-20 py-5">
        <div class="flex-1 flex justify-end">
            <button class="bg-primary font-inter text-4xl font-extrabold min-w-20 min-h-20 w-20 h-20 rounded-xl border-black border-2 cursor-pointer transition-transform duration-300 hover:rotate-12">
            L
        </button>
        </div>
    </header>

    <main class="px-12">
        <div class="mx-auto w-1/2 min-w-[36rem] px-6 rounded-lg border-2 border-black bg-background">
            <button
                class="group bg-white font-inter text-lg font-extrabold px-4 py-1 mr-6 rounded-full border-black border-2 flex items-center mx-auto gap-1 mt-4 cursor-pointer">
                <svg class="w-4 h-4 inline-block transition-transform duration-200 rotate-45 group-hover:rotate-[135deg]"
                    viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path d="M10 1H6V6L1 6V10H6V15H10V10H15V6L10 6V1Z" />
                </svg>
                CLOSE
            </button>

            <h1 class="font-inter font-extrabold text-2xl px-12 pt-6 pb-2">TITLE</h1>
            <input placeholder="Old title" class="rounded-lg border-black border-2 h-10 px-4 w-full cursor-text"></input>

            <h1 class="font-inter font-extrabold text-2xl px-12 pt-6 pb-2">DESCRIPTION</h1>
            <textarea placeholder="Old description" class="rounded-lg border-black border-2 h-10 px-4 py-2 mb-4 w-full h-32 cursor-text"></textarea>

            <div class="flex items-center justify-between">
                <div
                    class="bg-white font-inter text-lg font-extrabold w-fit px-4 py-1 mr-6 mb-8 rounded-full border-black border-2 hover:bg-progress cursor-pointer">
                    IN PROGRESS
                </div>
                <h2 class="font-inter font-semibold text-lg mr-6 mb-8 text-text-secondary">Created at <b class="text-black">12/12/2024</b>
                </h2>
            </div>
            <div class="flex-1 flex justify-center mb-6">
                <button
                    class="bg-white font-inter text-4xl font-extrabold py-4 px-6 rounded-full border-black border-2 hover:bg-primary cursor-pointer">
                    EDIT
                </button>
            </div>
        </div>
    </main>
