<header class="sticky top-0 z-10 grid grid-cols-3 items-center px-20 py-5 mb-5 bg-background-secondary border-b-2 border-black">
    <div class="justify-self-start">
        <a href="/task/create" class="flex items-center justify-center gap-3 px-6 py-4 bg-primary border-2 border-black rounded-full cursor-pointer font-inter text-4xl font-extrabold group">
            <svg class="inline-block w-6 h-6 transition-transform duration-300 group-hover:rotate-90" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path d="M10 1H6V6L1 6V10H6V15H10V10H15V6L10 6V1Z" />
            </svg>
            NEW TASK
        </a>
    </div>

    <div class="flex gap-5 justify-self-center">
        <a href="/" class="relative flex items-center justify-center h-12 overflow-hidden bg-white border-2 border-black rounded-full cursor-pointer transition-all duration-300 group <?= $this->status == '' ? 'w-20' : 'w-12 hover:w-20' ?> ? 'w-20' : 'w-12 hover:w-20' ?>">
            <span class="absolute inset-0 flex items-center justify-center whitespace-nowrap font-inter font-bold transition-opacity duration-300 <?= $this->status == '' ? 'text-black opacity-100' : 'text-black opacity-0 group-hover:opacity-100' ?>">
                ALL
            </span>
        </a>

        <a href="/?status=<?= TaskStatus::PENDING->value ?>" class="relative flex items-center justify-center h-12 overflow-hidden bg-pending border-2 border-black rounded-full cursor-pointer transition-all duration-300 group <?= $this->status === 'pending' ? 'w-28' : 'w-12 hover:w-28' ?>">
            <span class="absolute inset-0 flex items-center justify-center whitespace-nowrap font-inter font-bold transition-opacity duration-300 <?= $this->status === 'pending' ? 'text-white opacity-100' : 'text-white opacity-0 group-hover:opacity-100' ?>">
                PENDING
            </span>
        </a>

        <a href="/?status=<?= TaskStatus::PROGRESS->value ?>" class="relative flex items-center justify-center h-12 overflow-hidden bg-progress border-2 border-black rounded-full cursor-pointer transition-all duration-300 group <?= $this->status === 'in-progress' ? 'w-36' : 'w-12 hover:w-36' ?>">
            <span class="absolute inset-0 flex items-center justify-center whitespace-nowrap font-inter font-bold transition-opacity duration-300 <?= $this->status === 'in-progress' ? 'text-black opacity-100' : 'text-black opacity-0 group-hover:opacity-100' ?>">
                IN PROGRESS
            </span>
        </a>

        <a href="/task/<?= TaskStatus::COMPLETED->value ?>" class="relative flex items-center justify-center w-12 h-12 overflow-hidden bg-primary border-2 border-black rounded-full cursor-pointer transition-all duration-300 hover:w-36 group">
            <span class="absolute inset-0 flex items-center justify-center whitespace-nowrap font-inter font-bold opacity-0 transition-opacity duration-300 group-hover:opacity-100">
                COMPLETED
            </span>
        </a>
    </div>

    <div></div>
</header>

<main class="grid grid-cols-4 gap-4 px-12 bg-background-secondary">
    <?php foreach ($this->tasks as $task) : ?>
        <?php $status = TaskStatus::from($task['status']); ?>
        <div class="flex flex-col bg-white border-2 border-black rounded-lg">
            <a href=/task/<?= $task['id'] ?>>
                <div class="flex items-center justify-between">
                    <h1 class="px-8 py-4 font-inter text-2xl font-extrabold underline truncate hover:text-gray-600"><?= htmlspecialchars($task['title']) ?></h1>

                    <div class="flex items-center justify-center w-8 h-8 mr-4 border-2 border-black rounded-xl shrink-0 <?= $status->getColor() ?>"></div>
                </div>
            </a>

            <div class="flex-1 px-8 pb-4 overflow-hidden">
                <p class="font-inter text-base line-clamp-6"><?= nl2br(htmlspecialchars($task['description'])); ?></p>
            </div>

            <div class="flex items-center px-8 pb-4">
                <p class="font-inter text-sm text-text-secondary">Created at <b class="text-black"><?= htmlspecialchars($task['createdAt']) ?></b> by <b class="text-black"><?= htmlspecialchars($task['user']) ?></b></p>
            </div>

            <div class="flex justify-center pb-4 mt-auto">
                <form action="/task/status" method="POST">
                    <input type="hidden" name="id" value="<?= $task['id'] ?>">

                    <input type="hidden" name="status" value="<?= $status->getNextStatus()->value ?>">

                    <input type="hidden" name="redirect" value="/">

                    <button type="submit" class="bg-white border-2 border-black rounded-full cursor-pointer transition-colors duration-200 hover:bg-primary">
                        <p class="px-3 py-1 font-inter font-extrabold"><?= $status->getButtonLabel() ?></p>
                    </button>
                </form>
            </div>
        </div>
    <?php endforeach; ?>
</main>

<footer class="px-20 py-11 bg-background-secondary"></footer>