<header class="px-20 py-5 mb-5 grid grid-cols-3 items-center bg-background-secondary sticky top-0 z-10 border-b-2 border-black">
    <div class="justify-self-start">
        <a href="/task/create" class="group bg-primary font-inter text-4xl font-extrabold py-4 px-6 rounded-full border-black border-2 cursor-pointer flex items-center justify-center gap-3">
            <svg class="w-6 h-6 inline-block transition-transform duration-300 group-hover:rotate-90" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path d="M10 1H6V6L1 6V10H6V15H10V10H15V6L10 6V1Z" />
            </svg>
            NEW TASK
        </a>
    </div>

    <div class="justify-self-center flex gap-5">
        <a href="/"
            class="group relative h-12 bg-white rounded-full border-black border-2 flex items-center justify-center overflow-hidden transition-all duration-300 cursor-pointer
                <?= $this->status == '' ? 'w-20' : 'w-12 hover:w-20' ?> ? 'w-20' : 'w-12 hover:w-20' ?>">
            <span class="absolute inset-0 flex items-center justify-center whitespace-nowrap font-inter font-bold transition-opacity duration-300
                <?= $this->status == '' ? 'text-black opacity-100' : 'text-black opacity-0 group-hover:opacity-100' ?>">
                ALL
            </span>
        </a>
        <a href="/?status=<?= TaskStatus::PENDING->value ?>"
            class="group relative h-12 bg-pending rounded-full border-black border-2 flex items-center justify-center overflow-hidden transition-all duration-300 cursor-pointer
                <?= $this->status === 'pending' ? 'w-28' : 'w-12 hover:w-28' ?>">
            <span class="absolute inset-0 flex items-center justify-center whitespace-nowrap font-inter font-bold transition-opacity duration-300
                <?= $this->status === 'pending' ? 'text-white opacity-100' : 'text-white opacity-0 group-hover:opacity-100' ?>">
                PENDING
            </span>
        </a>
        <a href="/?status=<?= TaskStatus::PROGRESS->value ?>"
            class="group relative h-12 bg-progress rounded-full border-black border-2 flex items-center justify-center overflow-hidden transition-all duration-300 cursor-pointer
                <?= $this->status === 'in-progress' ? 'w-36' : 'w-12 hover:w-36' ?>">
            <span class="absolute inset-0 flex items-center justify-center whitespace-nowrap font-inter font-bold transition-opacity duration-300
                <?= $this->status === 'in-progress' ? 'text-black opacity-100' : 'text-black opacity-0 group-hover:opacity-100' ?>">
                IN PROGRESS
            </span>
        </a>
        <a href="/task/<?= TaskStatus::COMPLETED->value ?>" class="group relative w-12 h-12 bg-primary rounded-full border-black border-2 flex items-center justify-center overflow-hidden transition-all duration-300 hover:w-36 cursor-pointer">
            <span class="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300 whitespace-nowrap font-inter font-bold">COMPLETED</span>
        </a>
    </div>
    <div></div>
</header>

<main class="px-12 grid grid-cols-4 gap-4 bg-background-secondary">
    <?php foreach ($this->tasks as $task) : ?>
        <?php $status = TaskStatus::from($task['status']); ?>
        <div class="bg-white rounded-lg border-black border-2 flex flex-col">
            <a href=/task/<?= $task['id'] ?>>
                <div class="flex justify-between items-center">
                    <h1 class="font-inter font-extrabold text-2xl px-8 py-4 underline hover:text-gray-600 truncate"><?= htmlspecialchars($task['title']) ?></h1>
                    <div class="<?= $status->getColor() ?> rounded-xl border-black border-2 w-8 h-8 flex items-center justify-center mr-4 shrink-0"></div>
                </div>
            </a>
            <div class="overflow-hidden px-8 pb-4 flex-1">
                <p class="font-inter text-base line-clamp-6"><?= nl2br(htmlspecialchars($task['description'])); ?></p>
            </div>
            <div class="flex items-center px-8 pb-4">
                <p class="font-inter text-text-secondary text-sm">Created at <b class="text-black"><?= htmlspecialchars($task['createdAt']) ?></b> by <b class="text-black"><?= htmlspecialchars($task['user']) ?></b></p>
            </div>
            <div class="flex justify-center pb-4 mt-auto">
                <form action="/task/status" method="POST">
                    <input type="hidden" name="id" value="<?= $task['id'] ?>">
                    <input type="hidden" name="status" value="<?= $status->getNextStatus()->value ?>">
                    <input type="hidden" name="redirect" value="/">

                    <button type="submit" class="bg-white rounded-full border-black border-2 hover:bg-primary transition-colors duration-200 cursor-pointer">
                        <p class="font-inter font-extrabold px-3 py-1"><?= $status->getButtonLabel() ?></p>
                    </button>
                </form>
            </div>
        </div>
    <?php endforeach; ?>
</main>

<footer class="px-20 py-11 bg-background-secondary"></footer>