<header class="px-20 py-5 mb-5 flex items-center bg-background-secondary sticky top-0 z-10 border-b-2 border-black">
    <div class="flex-1 flex justify-start">
        <a href="/task/create" class="group bg-primary font-inter text-4xl font-extrabold py-4 px-6 rounded-full border-black border-2 cursor-pointer flex items-center justify-center gap-3">
            <svg class="w-6 h-6 inline-block transition-transform duration-300 group-hover:rotate-90" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path d="M10 1H6V6L1 6V10H6V15H10V10H15V6L10 6V1Z" />
            </svg>
            NEW TASK
        </a>
    </div>

    <div class="flex-1 flex justify-center gap-5">
        <a href="/" class="group relative w-12 h-12 bg-white rounded-full border-black border-2 flex items-center justify-center overflow-hidden transition-all duration-300 hover:w-20 cursor-pointer">
            <span class="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300 whitespace-nowrap font-inter font-bold">ALL</span>
        </a>
        <a href="/?status=<?= TaskStatus::PENDING->value ?>" class="group relative w-12 h-12 bg-pending rounded-full border-black border-2 flex items-center justify-center overflow-hidden transition-all duration-300 hover:w-28 cursor-pointer">
            <span class="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300 whitespace-nowrap font-inter font-bold text-white">PENDING</span>
        </a>
        <a href="/?status=<?= TaskStatus::PROGRESS->value ?>" class="group relative w-12 h-12 bg-progress rounded-full border-black border-2 flex items-center justify-center overflow-hidden transition-all duration-300 hover:w-36 cursor-pointer">
            <span class="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300 whitespace-nowrap font-inter font-bold">IN PROGRESS</span>
        </a>
        <a href="/task/<?= TaskStatus::COMPLETED->value ?>" class="group relative w-12 h-12 bg-primary rounded-full border-black border-2 flex items-center justify-center overflow-hidden transition-all duration-300 hover:w-36 cursor-pointer">
            <span class="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300 whitespace-nowrap font-inter font-bold">COMPLETED</span>
        </a>
    </div>

    <div class="flex-1 flex justify-end">
        <a class="bg-primary font-inter text-4xl font-extrabold min-w-20 min-h-20 w-20 h-20 rounded-xl border-black border-2 cursor-pointer transition-transform duration-300 hover:rotate-12">
            L
        </a>
    </div>
</header>

<main class="px-12 grid grid-cols-4 gap-4 bg-background-secondary">
    <?php if (count($this->tasks) === 0): ?>
        <div class=" flex items-center gap-3 ml-32">
            <svg
                class="w-12 h-12 rotate-90 -translate-y-2"
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round">
                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                <path d="M18 6v6a3 3 0 0 1 -3 3h-10l4 -4m0 8l-4 -4" />
            </svg>

            <h1 class="font-inter text-xl font-extrabold">
                ADD YOUR FIRST TASK!
            </h1>
        </div>
    <?php else: ?>
        <?php foreach ($this->tasks as $task) : ?>
            <?php $status = TaskStatus::from($task['status']); ?>
            <div class="bg-white rounded-lg border-black border-2 flex flex-col">
                <a href=/task/<?= $task['id'] ?>>
                    <div class="flex justify-between items-center">
                        <h1 class="font-inter font-extrabold text-2xl px-8 py-4 underline hover:text-gray-600"><?= htmlspecialchars($task['title']) ?></h1>
                </a>
                <div class="<?= $status->getColor() ?> rounded-xl border-black border-2 w-8 h-8 flex items-center justify-center mr-4 shrink-0"></div>
            </div>
            <div class="overflow-hidden px-8 pb-4 flex-1">
                <p class="font-inter text-base line-clamp-6"><?= nl2br(htmlspecialchars($task['description'])); ?></p>
            </div>
            <div class="flex items-center px-4 pb-4">
                <p class="font-inter text-text-secondary text-sm ml-auto">Created at <b class="text-black"><?= $task['createdAt'] ?></b> by <b class="text-black"><?= $task['userId'] ?></b></p>
            </div>
            <div class="flex justify-center pb-4 mt-auto">
                <form action="/task/status" method="POST">
                    <input type="hidden" name="id" value="<?= $task['id'] ?>">
                    <input type="hidden" name="status" value="<?= $status->getNextStatus()->value ?>">
                    <input type="hidden" name="redirect" value="/">

                    <button type="submit" class="bg-white rounded-full border-black border-2 hover:bg-primary transition-colors duration-200 cursor-pointer">
                        <p class="font-inter font-extrabold px-3 py-1"><?= $status->getButtonLabel() ?></p>
                    </button>
                </form>
            </div>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>
</main>

<footer class="px-20 py-11 bg-background-secondary"></footer>